

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-s3-clone-deployment
  labels:
    app: my-s3-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-s3-clone
  template:
    metadata:
      labels:
        app: my-s3-clone
    spec:
      containers:
        - name: my-s3-clone
          image: yonathan-darmon/ci-cd-kube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
